MVCEjemploLogin/Controllers/EmpleadoController.cs
using Models;
using NegocioBusiness;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UI_MVCNegocios.ViewModels;

namespace MVCEjemploLogin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EmpleadoController : Controller
    {
        ABMEmpleado db = new ABMEmpleado();
        ABMNegocio dbN = new ABMNegocio();
        // GET: Empleado
        [AllowAnonymous]
        public ActionResult Index(String searchString)
        {
            List<EmpleadoViewModel> empleados = new List<EmpleadoViewModel>();
            db.GetEmpleados().ForEach(x => empleados.Add(new EmpleadoViewModel(x)));

            if (!String.IsNullOrEmpty(searchString))
            {
               empleados = empleados.Where(e => e.Nombre.Contains(searchString)).ToList();

            }

            return View(empleados);
        }

        // GET: Empleado/Details/5
        public ActionResult Details(int id)
        {
            return View(new EmpleadoViewModel(db.GetEmpleado(id)));
        }

        // GET: Empleado/Create
        public ActionResult Create()
        {
            ViewBag.Id_Negocio = new SelectList(dbN.GetNegocios(), "Id", "Nombre");
            return View();
        }

        // POST: Empleado/Create
        [HttpPost]
        public ActionResult Create(EmpleadoViewModel empleado)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Empleado e = empleado.aEmpleado();
                    db.AddEmpleado(e, dbN.GetNegocio(e.Id_Negocio));
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View(empleado);
            }
        }

        // GET: Empleado/Edit/5
        public ActionResult Edit(int id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var empleado = db.GetEmpleado(id);

            if(empleado == null)
            {
                return HttpNotFound();
            }
            return View(new EmpleadoViewModel(empleado));
        }

        // POST: Empleado/Edit/5
        [HttpPost]
        public ActionResult Edit(EmpleadoViewModel empleado)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var e = empleado.aEmpleado();
                    db.UpdateEmpleado(e);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Empleado/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var empleado = db.GetEmpleado(id);

            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(new EmpleadoViewModel(empleado));
        }

        // POST: Empleado/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var empleado = db.GetEmpleado(id);
            db.RemoveEmpleado(empleado);
            return RedirectToAction("Index");

        }
    }
}

MVCEjemploLogin/Controllers/NegocioController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using NegocioBusiness;
using System.Net;
using UI_MVCNegocios.ViewModels;
using Models;
using System;
using System.Linq;

namespace MVCEjemploLogin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class NegocioController : Controller
    {
        ABMNegocio db = new ABMNegocio();

        // GET: Negocio
        [AllowAnonymous]
        public ActionResult Index(string searchString)
        {
            List<NegocioViewModel> negocios = new List<NegocioViewModel>(); 
            db.GetNegocios().ForEach(x => negocios.Add(new NegocioViewModel(x)));

            if (!String.IsNullOrEmpty(searchString))
            {
                negocios = negocios.Where(n => n.Nombre.Contains(searchString)).ToList();
                                       
            }

            return View(negocios);
        }

        // GET: Negocio/Details/5
        public ActionResult Details(int id)
        {
            return View(new NegocioViewModel(db.GetNegocio(id)));
        }

        // GET: Negocio/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Negocio/Create
        [HttpPost]
        public ActionResult Create(NegocioViewModel negocio)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var n = negocio.aNegocio();
                    db.AddNegocio(n);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View(negocio);
            }
        }

        // GET: Negocio/Edit/5
        public ActionResult Edit(int id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var negocio = db.GetNegocio(id);
            if(negocio == null)
            {
                return HttpNotFound();
            }
            return View(new NegocioViewModel(negocio));
        }

        // POST: Negocio/Edit/5
        [HttpPost]
        public ActionResult Edit(NegocioViewModel negocio)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var n = negocio.aNegocio();
                    db.UpdateNegocio(n);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View(negocio);
            }
        }

        // GET: Negocio/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var negocio = db.GetNegocio(id);
            if (negocio == null)
            {
                return HttpNotFound();
            }
            return View(new NegocioViewModel(negocio));
        }

        // POST: Negocio/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var negocio = db.GetNegocio(id);
           db.RemoveNegocio(negocio);
           return RedirectToAction("Index");
                
        }
        //GET: Negocio/EmpleadosPorNegocio/5
        public ActionResult EmpleadosPorNegocio(int id)
        {
            List<EmpleadoViewModel> vista = new List<EmpleadoViewModel>();
            db.FilterNegocio(id).ForEach(x => vista.Add(new EmpleadoViewModel(x)));
            return View(vista);
        }
    }
}

MVCEjemploLogin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

   <style>
       body {
           background-image: url('../Content/banner-03.jpg');
           background-position: fixed;
           background-repeat: no-repeat;
           background-size: cover;
       }
       #contenido{
           background-color: white;
           margin-top: 20px;
           border-radius: 10px;
       }
   </style>

</head>
<body >
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC Login", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Negocios", "Index", "Negocio")</li>
                    <li>@Html.ActionLink("Empleados", "Index", "Empleado")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" id="contenido">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>